// JavaScript Document
$('#intro-chay').owlCarousel({
    loop:true,
    margin:30,
    nav:true,
	autoplay:true,
	autoplayTimeout:5000,
	smartSpeed:2000,
    responsive:{
        0:{
            items:1
        },
        600:{
            items:1
        },
        1000:{
            items:1
        }
    }
})